# This is a basic workflow to help you get started with Actions

name: 小说转换音频

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [opened, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  transferToMusic:
    if: github.event.issue.user.login == 'zhangtao103239'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.1
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.x # optional, default is 3.x
          # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
          cache: pip # optional
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64 # optional
          # Used to pull python distributions from actions/python-versions. Since there's a default, this is typically not supplied by the user.
          token: ${{ github.token }} # optional, default is ${{ github.token }}
      - name: run-script
        run: |
          pip install -r requirements.txt
          python novel2audio.py -h${{secrets.SF_HOSTURL}} -u${{secrets.SF_USERNAME}} -p${{secrets.SF_PASSWORD}} -k${{secrets.MS_CLIENT_TOKEN}} -t${{github.event.issue.body}} -n${{github.event.issue.title}} -r${{secrets.SF_REPO_ID}} -d${{secrets.SF_UPLOAD_DIR}} -m${{secrets.SF_TXT_HOST_URL}}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: audio # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: "*.mp3"
          # The desired behavior if no files are found using the provided path.
          retention-days: 1 # optional

